# Generated by Django 4.1.7 on 2023-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_emp_comm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="comm",
            field=models.IntegerField(null=True),
        ),
    ]
